import type { GrammarTopic } from "./ai/prompts";

export const GRAMMAR_TOPICS: GrammarTopic[] = [
  {
    id: "perfekt-praeteritum",
    title: "Perfekt vs. Präteritum",
    description: "Quando usar cada tempo verbal no passado",
    examples: ["Ich habe gegessen (Perfekt)", "Ich aß (Präteritum)", "Er ist gegangen / Er ging"],
    difficulty: 2,
    examRelevance: "high",
  },
  {
    id: "konjunktiv-ii",
    title: "Konjunktiv II",
    description: "Subjuntivo para desejos, condições irreais e polidez",
    examples: ["Ich würde gern...", "Wenn ich könnte, würde ich...", "Könnten Sie mir helfen?"],
    difficulty: 3,
    examRelevance: "high",
  },
  {
    id: "nebensaetze",
    title: "Nebensätze (weil, dass, obwohl, wenn, als, ob)",
    description: "Orações subordinadas — verbo vai para o final",
    examples: ["Ich lerne Deutsch, weil ich nach Deutschland möchte.", "Obwohl es regnet, gehe ich spazieren."],
    difficulty: 2,
    examRelevance: "critical",
  },
  {
    id: "relativsaetze",
    title: "Relativsätze",
    description: "Orações relativas com der/die/das/den/dem/deren",
    examples: ["Das ist der Mann, der mir geholfen hat.", "Die Stadt, in der ich wohne, ist schön."],
    difficulty: 3,
    examRelevance: "high",
  },
  {
    id: "passiv",
    title: "Passiv (werden + Partizip II)",
    description: "Voz passiva em alemão",
    examples: ["Das Haus wird gebaut.", "Die E-Mail wurde geschickt.", "Der Patient wird untersucht."],
    difficulty: 3,
    examRelevance: "medium",
  },
  {
    id: "praepositionen",
    title: "Wechselpräpositionen (Dativ/Akkusativ)",
    description: "Preposições que mudam caso: in, an, auf, über, unter, vor, hinter, neben, zwischen",
    examples: ["Ich gehe in den Park. (Akk/Wohin?)", "Ich bin im Park. (Dat/Wo?)"],
    difficulty: 2,
    examRelevance: "critical",
  },
  {
    id: "reflexive-verben",
    title: "Reflexive Verben",
    description: "Verbos reflexivos com sich",
    examples: ["Ich freue mich.", "Er interessiert sich für Medizin.", "Wir treffen uns morgen."],
    difficulty: 2,
    examRelevance: "high",
  },
  {
    id: "indirekte-rede",
    title: "Indirekte Rede (Konjunktiv I)",
    description: "Discurso indireto",
    examples: ["Er sagte, er sei krank.", "Sie meinte, sie habe keine Zeit."],
    difficulty: 3,
    examRelevance: "medium",
  },
  {
    id: "adjektivdeklination",
    title: "Adjektivdeklination",
    description: "Declinação de adjetivos (com/sem artigo)",
    examples: ["der große Mann", "ein großer Mann", "großer Mann"],
    difficulty: 3,
    examRelevance: "high",
  },
  {
    id: "konnektoren",
    title: "Konnektoren (deshalb, trotzdem, außerdem...)",
    description: "Conectores que mudam a posição do verbo",
    examples: ["Deshalb lerne ich Deutsch.", "Trotzdem gehe ich spazieren.", "Ich lerne Deutsch, deshalb..."],
    difficulty: 2,
    examRelevance: "critical",
  },
  {
    id: "verben-mit-praepositionen",
    title: "Verben mit Präpositionen",
    description: "Verbos que exigem preposições fixas (sich freuen auf/über, warten auf, denken an)",
    examples: ["Ich freue mich auf den Urlaub.", "Er wartet auf den Bus.", "Ich denke an dich."],
    difficulty: 2,
    examRelevance: "critical",
  },
  {
    id: "artikel-genus",
    title: "Artikel und Genus (der/die/das)",
    description: "Gênero dos substantivos — regras, padrões e exceções",
    examples: ["der Computer, die Lampe, das Mädchen", "der -ling (Frühling)", "die -ung (Wohnung)", "das -chen (Mädchen)"],
    difficulty: 1,
    examRelevance: "critical",
  },
  {
    id: "dativ-akkusativ",
    title: "Dativ vs. Akkusativ",
    description: "Quando usar cada caso — verbos, preposições e regras",
    examples: ["Ich gebe dem Mann das Buch.", "Ich sehe den Mann.", "mit dem Auto (Dat)", "für den Chef (Akk)"],
    difficulty: 2,
    examRelevance: "critical",
  },
  {
    id: "modalverben",
    title: "Modalverben (können, müssen, sollen, dürfen, wollen, möchten)",
    description: "Verbos modais — conjugação, significado e uso",
    examples: ["Ich kann schwimmen.", "Du musst zum Arzt gehen.", "Darf ich fragen?", "Sie sollen mehr trinken."],
    difficulty: 1,
    examRelevance: "high",
  },
  {
    id: "infinitivsaetze",
    title: "Infinitivsätze (zu + Infinitiv, um...zu, ohne...zu, statt...zu)",
    description: "Orações infinitivas com 'zu'",
    examples: ["Ich habe keine Lust, aufzuräumen.", "Er geht ins Fitnessstudio, um fit zu bleiben.", "Sie ging, ohne sich zu verabschieden."],
    difficulty: 2,
    examRelevance: "high",
  },
  {
    id: "komparativ-superlativ",
    title: "Komparativ und Superlativ",
    description: "Comparativo e superlativo — formas regulares e irregulares",
    examples: ["groß → größer → am größten", "gut → besser → am besten", "Berlin ist größer als München."],
    difficulty: 1,
    examRelevance: "high",
  },
  {
    id: "trennbare-verben",
    title: "Trennbare und untrennbare Verben",
    description: "Verbos separáveis e inseparáveis — prefixos e regras",
    examples: ["aufstehen → Ich stehe um 7 Uhr auf.", "verstehen → Ich verstehe das nicht.", "anfangen, einladen, zurückkommen"],
    difficulty: 1,
    examRelevance: "high",
  },
  {
    id: "temporale-praepositionen",
    title: "Temporale Präpositionen (am, im, um, seit, vor, nach, bis)",
    description: "Preposições temporais — quando usar cada uma",
    examples: ["am Montag, im Januar, um 8 Uhr", "seit zwei Jahren", "vor dem Frühstück", "nach der Arbeit"],
    difficulty: 1,
    examRelevance: "high",
  },
  {
    id: "plusquamperfekt",
    title: "Plusquamperfekt (hatte/war + Partizip II)",
    description: "Mais-que-perfeito — ações anteriores a outra ação passada",
    examples: ["Als ich ankam, hatte er schon gegessen.", "Nachdem sie gegangen war, rief er an."],
    difficulty: 3,
    examRelevance: "medium",
  },
  {
    id: "genitiv",
    title: "Genitiv (des/der/eines/einer)",
    description: "Caso genitivo — posse e preposições (wegen, trotz, während)",
    examples: ["Das Auto des Arztes.", "Trotz des Regens gingen wir spazieren.", "Während der Sprechstunde."],
    difficulty: 3,
    examRelevance: "medium",
  },
  {
    id: "wortstellung",
    title: "Wortstellung im Hauptsatz",
    description: "Ordem das palavras na frase principal — TMP, inversão, posição do verbo",
    examples: ["Ich gehe morgen ins Kino.", "Morgen gehe ich ins Kino.", "Temporal-Modal-Lokal"],
    difficulty: 1,
    examRelevance: "critical",
  },
];

export function getGrammarTopicById(id: string): GrammarTopic | undefined {
  return GRAMMAR_TOPICS.find((t) => t.id === id);
}
