import type { Scenario } from "./ai/prompts";

export const SCENARIOS: Scenario[] = [
  // ── Goethe B1 Sprechen Teil 1: Gemeinsam etwas planen ──
  {
    id: "geburtstag-planen",
    title: "Geburtstagsfeier planen",
    description: "Planeje uma festa de aniversário com um amigo",
    icon: "🎂",
    examPart: "Sprechen Teil 1",
    prompt: "Du bist ein Freund. Ihr plant zusammen eine Geburtstagsfeier. Diskutiert: Wo? Wann? Essen und Trinken? Musik? Gästeliste? Beginne natürlich.",
    suggestedVocab: ["einladen", "vorbereiten", "Geschenk", "Feier", "vorschlagen"],
  },
  {
    id: "ausflug-planen",
    title: "Ausflug planen",
    description: "Planeje um passeio de fim de semana",
    icon: "🚶",
    examPart: "Sprechen Teil 1",
    prompt: "Du bist ein Freund. Ihr plant einen Wochenendausflug. Diskutiert: Wohin? Wie kommt ihr hin? Was nehmt ihr mit? Was macht ihr dort? Beginne natürlich.",
  },
  // ── Sprechen Teil 2: Ein Thema präsentieren ──
  {
    id: "praesentation-gesundheit",
    title: "Präsentation: Gesundheit",
    description: "Apresente sobre o tema saúde",
    icon: "🏥",
    examPart: "Sprechen Teil 2",
    prompt: "Der Schüler soll eine kurze Präsentation über 'Gesundheit und Sport' halten. Stelle Rückfragen und reagiere auf die Präsentation. Hilf dabei, Redemittel zu üben: Meiner Meinung nach..., Ich möchte über... sprechen, Zum Schluss möchte ich sagen...",
  },
  // ── Alltagssituationen ──
  {
    id: "beim-arzt",
    title: "Beim Arzt",
    description: "Consulta médica — descreva sintomas",
    icon: "👨‍⚕️",
    examPart: "Alltagssituation",
    prompt: "Du bist ein Arzt in einer deutschen Praxis. Der Patient ruft an, um einen Termin zu vereinbaren und Symptome zu beschreiben. Verwende medizinische Alltagssprache auf B1-Niveau.",
    suggestedVocab: ["Symptome", "Termin vereinbaren", "Rezept", "Überweisung", "Untersuchung"],
  },
  {
    id: "wohnungssuche",
    title: "Wohnungssuche",
    description: "Procure apartamento",
    icon: "🏠",
    examPart: "Alltagssituation",
    prompt: "Du bist ein Vermieter. Jemand ruft wegen einer Wohnungsanzeige an. Beschreibe die Wohnung, nenne den Preis und beantworte Fragen zur Lage, Nebenkosten und zum Einzugstermin.",
  },
  {
    id: "beschwerde",
    title: "Beschwerde schreiben",
    description: "Reclame sobre produto/serviço",
    icon: "😤",
    examPart: "Alltagssituation",
    prompt: "Du bist Kundenservice-Mitarbeiter. Ein Kunde hat ein defektes Produkt erhalten und möchte sich beschweren. Sei professionell, frage nach Details und biete Lösungen an.",
  },
  {
    id: "vorstellungsgespraech",
    title: "Vorstellungsgespräch",
    description: "Entrevista de emprego",
    icon: "💼",
    examPart: "Alltagssituation",
    prompt: "Du bist Personalchef und führst ein Vorstellungsgespräch. Frage nach Erfahrung, Motivation, Stärken/Schwächen und Gehaltsvorstellungen. Reagiere natürlich auf Antworten.",
  },
  {
    id: "restaurant",
    title: "Im Restaurant",
    description: "Peça comida e interaja",
    icon: "🍽️",
    examPart: "Alltagssituation",
    prompt: "Du bist Kellner in einem deutschen Restaurant. Begrüße den Gast, empfehle Gerichte, erkläre Zutaten und nimm die Bestellung auf. Frage nach Allergien und Wünschen.",
  },
  {
    id: "reiseplanung",
    title: "Reiseplanung",
    description: "Planeje uma viagem",
    icon: "✈️",
    examPart: "Alltagssituation",
    prompt: "Du bist ein Reisebüro-Mitarbeiter. Hilf dem Kunden bei der Reiseplanung: Flüge, Hotels, Sehenswürdigkeiten, Versicherung. Frage nach Budget und Vorlieben.",
  },
  {
    id: "meinung",
    title: "Meinung äußern",
    description: "Debata um tema atual",
    icon: "💬",
    examPart: "Diskussion",
    prompt: "Führe eine Diskussion über ein aktuelles Thema. Wähle eines: Homeoffice vs. Büro, Soziale Medien, Umweltschutz im Alltag, Gesunde Ernährung. Frage nach Meinungen und bringe Gegenargumente.",
  },
  // ── Medical German (Bonus) ──
  {
    id: "medizinisch",
    title: "Medizinisches Deutsch",
    description: "Vocabulário médico em contexto",
    icon: "🩺",
    examPart: "Fachsprache",
    prompt: "Du bist ein deutscher Kollege auf einer Krankenstation. Diskutiere einen Patientenfall auf B1/B2-Niveau. Verwende medizinische Fachbegriffe, aber erkläre sie wenn nötig. Themen: Anamnese, Diagnose, Behandlungsplan.",
  },
  // ── Goethe B1 Sprechen Teil 1: Mehr Planungsszenarien ──
  {
    id: "umzug-planen",
    title: "Umzug planen",
    description: "Planeje uma mudança com um amigo",
    icon: "📦",
    examPart: "Sprechen Teil 1",
    prompt: "Du bist ein Freund. Ihr plant zusammen einen Umzug. Diskutiert: Wann? Wer hilft? Braucht ihr ein Umzugsunternehmen? Was muss vorher erledigt werden? Beginne natürlich.",
    suggestedVocab: ["umziehen", "Karton", "Möbel", "Transporter", "Nachsendeauftrag"],
  },
  {
    id: "abschiedsfeier",
    title: "Abschiedsfeier organisieren",
    description: "Organize uma festa de despedida",
    icon: "🥂",
    examPart: "Sprechen Teil 1",
    prompt: "Du bist ein Kollege. Ein gemeinsamer Freund zieht weg. Ihr organisiert eine Abschiedsfeier. Diskutiert: Wo? Wann? Geschenk? Überraschung oder nicht? Beginne natürlich.",
    suggestedVocab: ["Abschied", "überraschen", "Erinnerung", "Geschenkidee", "organisieren"],
  },
  {
    id: "sportverein",
    title: "Sportverein beitreten",
    description: "Planeje entrar num clube esportivo",
    icon: "⚽",
    examPart: "Sprechen Teil 1",
    prompt: "Du bist ein Freund, der schon in einem Sportverein ist. Dein Gesprächspartner möchte beitreten. Diskutiert: Welche Sportart? Kosten? Trainingszeiten? Ausrüstung? Beginne natürlich.",
    suggestedVocab: ["Mitgliedschaft", "Beitrag", "trainieren", "Mannschaft", "Ausdauer"],
  },
  // ── Sprechen Teil 2: Mehr Präsentationsthemen ──
  {
    id: "praesentation-beruf",
    title: "Präsentation: Mein Beruf",
    description: "Apresente sobre sua profissão",
    icon: "👨‍⚕️",
    examPart: "Sprechen Teil 2",
    prompt: "Der Schüler soll eine kurze Präsentation über seinen Beruf als Arzt halten — warum er Medizin gewählt hat, Erfahrungen, Herausforderungen. Stelle Rückfragen und reagiere auf die Präsentation.",
  },
  {
    id: "praesentation-medien",
    title: "Präsentation: Soziale Medien",
    description: "Apresente sobre redes sociais",
    icon: "📱",
    examPart: "Sprechen Teil 2",
    prompt: "Der Schüler soll eine Präsentation über Soziale Medien halten — Vor- und Nachteile, persönliche Erfahrungen, Auswirkungen auf die Gesellschaft. Stelle Rückfragen und bringe Gegenargumente.",
  },
  {
    id: "praesentation-wohnen",
    title: "Präsentation: Wohnen in der Stadt",
    description: "Apresente sobre morar na cidade",
    icon: "🏙️",
    examPart: "Sprechen Teil 2",
    prompt: "Der Schüler soll eine Präsentation über 'Wohnen in der Stadt vs. auf dem Land' halten. Stelle Rückfragen zu Kosten, Lebensqualität, Verkehr, Natur. Reagiere natürlich auf Argumente.",
  },
  // ── Alltagssituationen: Erweitert ──
  {
    id: "behoerde",
    title: "Auf dem Amt",
    description: "Resolva assuntos no órgão público",
    icon: "🏛️",
    examPart: "Alltagssituation",
    prompt: "Du bist ein Beamter auf dem Ausländeramt. Der Gesprächspartner muss seine Aufenthaltserlaubnis verlängern. Frage nach Dokumenten, erkläre das Verfahren, nenne Wartezeiten und Kosten.",
    suggestedVocab: ["Aufenthaltserlaubnis", "Antrag", "Formular", "Personalausweis", "verlängern"],
  },
  {
    id: "nachbarn",
    title: "Probleme mit Nachbarn",
    description: "Resolva problemas com vizinhos",
    icon: "🏘️",
    examPart: "Alltagssituation",
    prompt: "Du bist ein Nachbar. Es gibt Probleme im Haus: Lärm, Müll, Parken. Diskutiert das Problem höflich und findet gemeinsam eine Lösung. Sei diplomatisch aber bestimmt.",
    suggestedVocab: ["Ruhezeiten", "Hausordnung", "stören", "Kompromiss", "Verständnis"],
  },
  {
    id: "bank",
    title: "Bei der Bank",
    description: "Abra conta ou resolva assuntos bancários",
    icon: "🏦",
    examPart: "Alltagssituation",
    prompt: "Du bist ein Bankangestellter. Ein Kunde möchte ein Girokonto eröffnen und hat Fragen zu Onlinebanking, EC-Karte, Überweisungen und Gebühren. Erkläre alles auf B1-Niveau.",
    suggestedVocab: ["Girokonto", "Überweisung", "Kontoauszug", "Gebühren", "Dauerauftrag"],
  },
  {
    id: "apotheke",
    title: "In der Apotheke",
    description: "Compre medicamentos na farmácia",
    icon: "💊",
    examPart: "Alltagssituation",
    prompt: "Du bist Apotheker. Ein Kunde kommt mit einem Rezept oder braucht ein rezeptfreies Medikament. Frage nach Symptomen, erkläre die Einnahme, Nebenwirkungen und Wechselwirkungen.",
    suggestedVocab: ["Rezept", "Nebenwirkungen", "Dosierung", "Tabletten", "Wechselwirkungen"],
  },
  {
    id: "elternabend",
    title: "Elternabend / Schulgespräch",
    description: "Participe de uma reunião escolar",
    icon: "🎒",
    examPart: "Alltagssituation",
    prompt: "Du bist Lehrer/in. Ein Elternteil kommt zum Elternabend, um über die Leistungen seines Kindes zu sprechen. Berichte über Stärken, Schwächen, Hausaufgaben und soziales Verhalten.",
    suggestedVocab: ["Zeugnis", "Leistung", "Hausaufgaben", "Klassenkamerad", "sich verbessern"],
  },
  {
    id: "versicherung",
    title: "Versicherung abschließen",
    description: "Contrate um seguro",
    icon: "🛡️",
    examPart: "Alltagssituation",
    prompt: "Du bist Versicherungsberater. Ein Kunde in Deutschland braucht Krankenversicherung und fragt nach Tarifen, Leistungen, gesetzlich vs. privat. Erkläre das deutsche System auf B1-Niveau.",
    suggestedVocab: ["Krankenversicherung", "Beitrag", "Leistungen", "Selbstbeteiligung", "gesetzlich"],
  },
  // ── Medical German: Erweitert ──
  {
    id: "anamnese",
    title: "Anamnese durchführen",
    description: "Conduza uma anamnese médica",
    icon: "📋",
    examPart: "Fachsprache",
    prompt: "Du bist Patient mit Bauchschmerzen, Übelkeit und Fieber seit 3 Tagen. Der Arzt (Schüler) führt eine Anamnese durch. Antworte realistisch, beschreibe Symptome wenn gefragt, erwähne Vorerkrankungen und Medikamente.",
    suggestedVocab: ["Anamnese", "Vorerkrankung", "Beschwerden", "Medikamenteneinnahme", "Allergien"],
  },
  {
    id: "uebergabe",
    title: "Patientenübergabe",
    description: "Faça uma passagem de caso entre colegas",
    icon: "🔄",
    examPart: "Fachsprache",
    prompt: "Du bist ein deutscher Arzt-Kollege. Der Schüler-Arzt übergibt dir einen Patienten am Schichtende. Stelle Rückfragen zu Diagnose, aktueller Therapie, offenen Befunden und Besonderheiten der Nacht.",
    suggestedVocab: ["Übergabe", "Befund", "Therapie", "Verlauf", "Visite"],
  },
  {
    id: "aufklaerung",
    title: "Patientenaufklärung",
    description: "Explique um procedimento ao paciente",
    icon: "📝",
    examPart: "Fachsprache",
    prompt: "Du bist Patient und brauchst eine kleine OP (z.B. Arthroskopie). Der Arzt (Schüler) muss dich aufklären: Was wird gemacht? Risiken? Narkose? Nachsorge? Stelle ängstliche Fragen.",
    suggestedVocab: ["Aufklärung", "Eingriff", "Risiken", "Narkose", "Einwilligung"],
  },
  {
    id: "notaufnahme",
    title: "In der Notaufnahme",
    description: "Atenda um paciente na emergência",
    icon: "🚑",
    examPart: "Fachsprache",
    prompt: "Du bist ein Patient mit starken Brustschmerzen in der Notaufnahme. Der Arzt (Schüler) muss schnell Anamnese machen, Differenzialdiagnosen bedenken und Untersuchungen anordnen. Sei ängstlich und frage nach.",
    suggestedVocab: ["Notaufnahme", "Brustschmerz", "EKG", "Blutabnahme", "stationär aufnehmen"],
  },
  // ── Diskussionsthemen ──
  {
    id: "ernaehrung",
    title: "Gesunde Ernährung",
    description: "Debata sobre alimentação saudável",
    icon: "🥗",
    examPart: "Diskussion",
    prompt: "Führe eine Diskussion über gesunde Ernährung: Bio vs. konventionell, Fleisch vs. vegetarisch, Fast Food, Kochen zu Hause. Frage nach der persönlichen Meinung und bringe Gegenargumente.",
  },
  {
    id: "technologie",
    title: "Technologie im Alltag",
    description: "Debata sobre tecnologia no dia a dia",
    icon: "💻",
    examPart: "Diskussion",
    prompt: "Diskutiere über Technologie: Sind Smartphones zu präsent? KI in der Medizin? Datenschutz? Kinder und Bildschirmzeit? Frage nach Erfahrungen und persönlichen Meinungen.",
  },
  {
    id: "umwelt",
    title: "Umweltschutz",
    description: "Debata sobre proteção ambiental",
    icon: "🌍",
    examPart: "Diskussion",
    prompt: "Diskutiere über Umweltschutz: Mülltrennung in Deutschland, Klimawandel, Elektroautos, Flugreisen, persönliche Verantwortung. Frage nach konkreten Maßnahmen und Meinungen.",
  },
  // ── Freies Gespräch (immer am Ende) ──
  {
    id: "frei",
    title: "Freies Gespräch",
    description: "Conversa livre",
    icon: "🗣️",
    examPart: "Frei",
    prompt: "Führe ein natürliches, freundliches Gespräch auf Deutsch über beliebige Themen. Passe dich dem B1-Niveau an. Sei neugierig und stelle interessante Fragen.",
  },
];

export function getScenarioById(id: string): Scenario | undefined {
  return SCENARIOS.find((s) => s.id === id);
}
