import type { SchreibenTask } from "./ai/prompts";

export const SCHREIBEN_TASKS: SchreibenTask[] = [
  {
    id: "einladung",
    title: "Einladung zur Feier",
    instruction: "Schreiben Sie eine E-Mail an Ihren Freund / Ihre Freundin.",
    situation: "Sie möchten Ihren Geburtstag feiern und Ihren Freund / Ihre Freundin einladen.",
    points: [
      "Warum schreiben Sie?",
      "Wann und wo ist die Feier?",
      "Was soll er/sie mitbringen?",
      "Wie kommt man dorthin?",
    ],
    wordCount: { min: 80, target: 120, max: 160 },
    register: "informal",
  },
  {
    id: "beschwerde-internet",
    title: "Beschwerde: Internetanschluss",
    instruction: "Schreiben Sie eine E-Mail an den Kundenservice.",
    situation: "Ihr Internetanschluss funktioniert seit einer Woche nicht richtig.",
    points: [
      "Warum schreiben Sie?",
      "Beschreiben Sie das Problem genau.",
      "Seit wann besteht das Problem?",
      "Was erwarten Sie (Lösung/Entschädigung)?",
    ],
    wordCount: { min: 80, target: 120, max: 160 },
    register: "formal",
  },
  {
    id: "urlaub-empfehlung",
    title: "Urlaubsempfehlung",
    instruction: "Schreiben Sie eine E-Mail an Ihren Freund.",
    situation: "Ihr Freund möchte in Ihrer Stadt/Region Urlaub machen und bittet um Tipps.",
    points: [
      "Warum schreiben Sie?",
      "Was kann man in Ihrer Stadt sehen/machen?",
      "Wo kann man gut essen?",
      "Wie ist das Wetter zu dieser Jahreszeit?",
    ],
    wordCount: { min: 80, target: 120, max: 160 },
    register: "informal",
  },
  {
    id: "sprachkurs",
    title: "Anmeldung Sprachkurs",
    instruction: "Schreiben Sie eine E-Mail an eine Sprachschule.",
    situation: "Sie möchten einen Deutschkurs besuchen und brauchen Informationen.",
    points: [
      "Warum schreiben Sie?",
      "Fragen Sie nach Kurszeiten und Preisen.",
      "Fragen Sie nach einem Einstufungstest.",
      "Fragen Sie nach Unterrichtsmaterialien.",
    ],
    wordCount: { min: 80, target: 120, max: 160 },
    register: "formal",
  },
  {
    id: "reparatur",
    title: "Reparatur in der Wohnung",
    instruction: "Schreiben Sie eine E-Mail an Ihren Vermieter.",
    situation: "In Ihrer Wohnung ist etwas kaputt (Heizung, Wasserhahn, Fenster).",
    points: [
      "Warum schreiben Sie?",
      "Beschreiben Sie das Problem.",
      "Seit wann besteht das Problem?",
      "Bitten Sie um einen Termin für die Reparatur.",
    ],
    wordCount: { min: 80, target: 120, max: 160 },
    register: "formal",
  },
  {
    id: "neue-arbeit",
    title: "Neuer Job",
    instruction: "Schreiben Sie eine E-Mail an einen Freund.",
    situation: "Sie haben eine neue Arbeitsstelle gefunden und möchten davon erzählen.",
    points: [
      "Was ist Ihre neue Arbeit?",
      "Wie haben Sie die Stelle gefunden?",
      "Was gefällt Ihnen an der neuen Arbeit?",
      "Was vermissen Sie an der alten Arbeit?",
    ],
    wordCount: { min: 80, target: 120, max: 160 },
    register: "informal",
  },
  // ── Formal: Mehr Beschwerden und Anfragen ──
  {
    id: "beschwerde-restaurant",
    title: "Beschwerde: Restaurant",
    instruction: "Schreiben Sie eine E-Mail an das Restaurant.",
    situation: "Sie hatten eine Reservierung für ein wichtiges Abendessen, aber der Service war sehr schlecht.",
    points: [
      "Wann waren Sie im Restaurant?",
      "Was genau war das Problem?",
      "Wie hat das Personal reagiert?",
      "Was erwarten Sie als Entschädigung?",
    ],
    wordCount: { min: 80, target: 120, max: 160 },
    register: "formal",
  },
  {
    id: "kuendigung-fitnessstudio",
    title: "Kündigung Fitnessstudio",
    instruction: "Schreiben Sie eine E-Mail an das Fitnessstudio.",
    situation: "Sie möchten Ihre Mitgliedschaft im Fitnessstudio kündigen.",
    points: [
      "Warum schreiben Sie?",
      "Nennen Sie Ihre Mitgliedsnummer und den Vertrag.",
      "Begründen Sie die Kündigung.",
      "Fragen Sie nach einer Bestätigung.",
    ],
    wordCount: { min: 80, target: 120, max: 160 },
    register: "formal",
  },
  {
    id: "bewerbung-praktikum",
    title: "Bewerbung: Praktikum",
    instruction: "Schreiben Sie eine E-Mail an ein Krankenhaus.",
    situation: "Sie möchten ein Praktikum in einem deutschen Krankenhaus machen und bewerben sich.",
    points: [
      "Warum schreiben Sie?",
      "Beschreiben Sie Ihre Qualifikationen und Erfahrung.",
      "Wann möchten Sie das Praktikum machen?",
      "Fragen Sie nach den nächsten Schritten.",
    ],
    wordCount: { min: 80, target: 120, max: 160 },
    register: "formal",
  },
  {
    id: "anfrage-verein",
    title: "Anfrage: Sportverein",
    instruction: "Schreiben Sie eine E-Mail an einen Sportverein.",
    situation: "Sie möchten einem Sportverein beitreten und brauchen Informationen.",
    points: [
      "Warum schreiben Sie?",
      "Fragen Sie nach Trainingszeiten.",
      "Fragen Sie nach Kosten und Mitgliedschaft.",
      "Fragen Sie nach einem Probetraining.",
    ],
    wordCount: { min: 80, target: 120, max: 160 },
    register: "formal",
  },
  // ── Informal: Mehr persönliche E-Mails ──
  {
    id: "krankenbesuch",
    title: "Freund im Krankenhaus",
    instruction: "Schreiben Sie eine E-Mail an einen Freund.",
    situation: "Ihr Freund liegt im Krankenhaus. Sie möchten ihn besuchen und aufmuntern.",
    points: [
      "Wie haben Sie davon erfahren?",
      "Wann möchten Sie ihn besuchen?",
      "Was bringen Sie mit?",
      "Wünschen Sie gute Besserung und machen Sie Mut.",
    ],
    wordCount: { min: 80, target: 120, max: 160 },
    register: "informal",
  },
  {
    id: "umzug-nachricht",
    title: "Umzug in neue Stadt",
    instruction: "Schreiben Sie eine E-Mail an einen Freund.",
    situation: "Sie sind gerade in eine neue Stadt gezogen und erzählen davon.",
    points: [
      "Warum sind Sie umgezogen?",
      "Wie ist Ihre neue Wohnung/Ihr neues Haus?",
      "Was gefällt Ihnen an der neuen Stadt?",
      "Laden Sie Ihren Freund zum Besuch ein.",
    ],
    wordCount: { min: 80, target: 120, max: 160 },
    register: "informal",
  },
  {
    id: "danke-geschenk",
    title: "Dankeschön für Geschenk",
    instruction: "Schreiben Sie eine E-Mail an Ihre Freundin.",
    situation: "Ihre Freundin hat Ihnen ein Geschenk zum Geburtstag geschickt.",
    points: [
      "Bedanken Sie sich für das Geschenk.",
      "Beschreiben Sie, warum es Ihnen gefällt.",
      "Erzählen Sie, wie Ihr Geburtstag war.",
      "Schlagen Sie ein Treffen vor.",
    ],
    wordCount: { min: 80, target: 120, max: 160 },
    register: "informal",
  },
  {
    id: "deutschkurs-erfahrung",
    title: "Deutschkurs-Erfahrung",
    instruction: "Schreiben Sie eine E-Mail an einen Freund.",
    situation: "Sie machen gerade einen Deutschkurs in Deutschland und erzählen davon.",
    points: [
      "Wie ist der Kurs? (Lehrer, Mitschüler, Schwierigkeit)",
      "Was lernen Sie gerade?",
      "Was finden Sie schwierig?",
      "Was machen Sie nach dem Unterricht?",
    ],
    wordCount: { min: 80, target: 120, max: 160 },
    register: "informal",
  },
  // ── Medical context ──
  {
    id: "termin-absagen",
    title: "Arzttermin absagen",
    instruction: "Schreiben Sie eine E-Mail an eine Arztpraxis.",
    situation: "Sie müssen einen vereinbarten Arzttermin absagen und bitten um einen neuen Termin.",
    points: [
      "Warum schreiben Sie?",
      "Nennen Sie den ursprünglichen Termin.",
      "Begründen Sie die Absage.",
      "Bitten Sie um einen neuen Termin (mit Wunschzeiten).",
    ],
    wordCount: { min: 80, target: 120, max: 160 },
    register: "formal",
  },
  {
    id: "arbeitszeugnis",
    title: "Arbeitszeugnis anfordern",
    instruction: "Schreiben Sie eine E-Mail an Ihren ehemaligen Arbeitgeber.",
    situation: "Sie brauchen ein Arbeitszeugnis von Ihrem letzten Arbeitgeber für eine Bewerbung in Deutschland.",
    points: [
      "Warum schreiben Sie?",
      "Von wann bis wann haben Sie dort gearbeitet?",
      "Was war Ihre Position?",
      "Bis wann brauchen Sie das Zeugnis?",
    ],
    wordCount: { min: 80, target: 120, max: 160 },
    register: "formal",
  },
];

export function getSchreibenTaskById(id: string): SchreibenTask | undefined {
  return SCHREIBEN_TASKS.find((t) => t.id === id);
}
